# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Timothy Gale
email: tim@timgale.me
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://timgale.me" # the base hostname & protocol for your site
twitter_username: timgale
github_username:  timgale
future: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

sass:
    sass_dir: _sass
