# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Gale · Product Designer
email: tim@timgale.me
description: The blog and portfolio of Tim Gale, Product Designer
repository: timgale/timgale.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timgale.me" # the base hostname & protocol for your site
twitter_username: timgale
github_username:  timgale
future: true
menuitems:
  - url: /writing/
    title: Writing
  - url: /Speaking/
    title: Speaking
  - url: /projects/
    title: Projects

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

# Sass settings
sass:
    sass_dir: _sass

# Collection settings
collections:
    projects:
      output: true
      permalink: /:collection/:title

# Plugins
plugins:
  - jekyll-seo-tag